### ISSUE TITLE
Error on KaMIS 

### ISSUE THREAD

**Issue by sagebei** [MaxiBoether/mis-benchmark-framework#2]
I was running `python main.py solve kamis './' './' `, but got this error:

[Errno 2] No such file or directory: PosixPath('/mis-benchmark-framework/solvers/kamis/KaMIS/deploy/redumis')

Do you know how this can be solved? Thank you.

**Comment by MaxiBoether** [comment]
Hey! Please excuse the late answer.

It appears that KaMIS was not built. I suppose that there is some trouble compiling KaMIS on your machine. Can you please try to build the KaMIS commit that we use manually, by running

```
git clone https://github.com/KarlsruheMIS/KaMIS
git checkout 791334ef6aebb2ccf005316258c043cca58923a0
bash compile_withcmake.sh
```

And show me the complete output? Then, we could figure out while it is not compiling for you. In general, if the steps above don't work on your machine, then the framework cannot run KaMIS. Furthermore, we only tested Linux, if you use Windows, things might break, and probably, I could not help you then.

**Comment by zxpekko** [comment]
Hello, could you share the dataset?  It seems that I don't know how to use data_generation.

**Comment by sagebei** [comment]
> Hey! Please excuse the late answer.
> 
> It appears that KaMIS was not built. I suppose that there is some trouble compiling KaMIS on your machine. Can you please try to build the KaMIS commit that we use manually, by running
> 
> ```
> git clone https://github.com/KarlsruheMIS/KaMIS
> git checkout 791334ef6aebb2ccf005316258c043cca58923a0
> bash compile_withcmake.sh
> ```
> 
> And show me the complete output? Then, we could figure out while it is not compiling for you. In general, if the steps above don't work on your machine, then the framework cannot run KaMIS. Furthermore, we only tested Linux, if you use Windows, things might break, and probably, I could not help you then.

Thank you for your reply. I was using the macos and it turned out that it is the laster xcode that caused the compiling errors. I used a linux machine and it works fine!

**Comment by MaxiBoether** [comment]
Alright, thank you for the report!
