### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by zxpekko** [MaxiBoether/mis-benchmark-framework#3]
Hello, could you share the dataset?  It seems that I don't know how to use data_generation.

**Comment by MaxiBoether** [comment]
Which exact dataset are you referring to? The random graphs we used are linked in the README file.

**Comment by sagebei** [comment]
`(venv) [acw554@frontend8 mis-benchmark-framework]$ python main.py -h
usage: main.py [-h] [--loglevel {DEBUG,INFO,WARNING,ERROR}] [--self_loops] {train,solve,gendata} ...

Testbench for MIS solvers.

positional arguments:
  {train,solve,gendata}
                        sub-command help
    train               Model training
    solve               Call a solver
    gendata             Generate input data

optional arguments:
  -h, --help            show this help message and exit
  --loglevel {DEBUG,INFO,WARNING,ERROR}
                        Verbosity of logging (DEBUG/INFO/WARNING/ERROR)
  --self_loops          Enable self loops addition (in input data) for GCN-based model.`

@zxpekko Probably you can find more information in the terminal by exploring these options, and post your question with details such that the author can give you the exact help you might need.

**Comment by zxpekko** [comment]
Thank you for your reply. I did find some datasets in readme. This is what I am referring to at present. I will consider the following issues. Thank you very much for your reply.@MaxiBoether

**Comment by zxpekko** [comment]
Thank you for your reply. I will seriously consider your suggestions. Thank you very much for your reply.@sagebei

**Comment by MaxiBoether** [comment]
Thanks. Let me know if there are any issues running the code. Closing this for now.
