### ISSUE TITLE
On which dataset is the pretrained weight trained?

### ISSUE THREAD

**Issue by zdhNarsil** [MaxiBoether/mis-benchmark-framework#6]
Thank you for providing public data and pretrained weights. I wonder on which dataset is the pretrained weight trained?

**Comment by MaxiBoether** [comment]
Hi! Thanks for your question. To which exact solver are you referring? For the DGL tree search, we trained on SATLIB. 

Section 3.1 in our paper provides some more background information on the training process that we did. Does that help?

**Comment by zdhNarsil** [comment]
I am particularly referring to the pretrained weight of LwD method, but also curious of the training for intel/dgl.

I feel confused between the two possibilities:
1. A method is trained on SATLIB and test on all other datasets
2. A method is trained and evaluated on the same data distribution. For example, LwD is trained on one fold of ER 50-100 data and evaluated on another fold of ER 50-100 data.

Which one is correct?

**Comment by MaxiBoether** [comment]
For the tree search, we train on 39500 SATLIB instances and test on 500 (see Appendix E). This means that the SATLIB evaluation is done for graphs from the same distribution. For evaluating other graphs, we use the SATLIB network as well, similar to the Li et al. (2018) paper, which evaluates the out of distribution generalization capabilities.

LwD is trained for 20000 PPO iterations on SATLIB as well (see Section 3.2). The hyperparameters are found in Appendix A.

Does that help :)?

**Comment by zdhNarsil** [comment]
Thanks for the helpful clarification 😄!

**Comment by MaxiBoether** [comment]
You're welcome! If you have any further question, don't hesitate to ask again!
